INSERT INTO `#__app_sch_configuation` (`id`, `config_key`, `config_value`) VALUES
(1,'business_name','Konas CF'),
(2,'value_string_email_address','acosta@mygroup.cl'),
(3,'mobile_notification','+56983084387'),
(4,'date_time_format','d.m.Y, H:i'),
(5,'date_format','d.m.Y'),
(6,'time_format','g:i A'),
(7,'load_bootstrap','1'),
(8,'csv_separator',';'),
(9,'currency_format','CLP'),
(10,'currency_symbol_position','0'),
(11,'allow_multiple_timezones','0'),
(12,'timezone1',''),
(13,'timezone2',''),
(14,'timezone3',''),
(15,'timezone4',''),
(16,'timezone5',''),
(17,'integrate_gcalendar','0'),
(18,'gcalendar_width','700'),
(19,'gcalendar_height','600'),
(20,'footer_content','Developed by MyGroup'),
(21,'meta_keyword',''),
(22,'meta_desc',''),
(23,'value_sch_reminder_enable','1'),
(24,'value_sch_reminder_email_before','3'),
(25,'employee_acl_group','10'),
(26,'employee_change_availability','1'),
(27,'disable_timeslot','1'),
(28,'multiple_work','1'),
(29,'allow_registered_only','1'),
(30,'allow_registration','1'),
(31,'integrate_user_profile','1'),
(32,'group_payment',''),
(33,'step_format','60'),
(34,'disable_payments','0'),
(35,'enable_tax','0'),
(36,'tax_payment',''),
(37,'deposit_payment','25'),
(38,'early_bird','0'),
(39,'enable_slots_discount','1'),
(40,'disable_payment_order_status','S'),
(41,'enable_cardtypes',''),
(42,'value_enum_email_confirmation','2'),
(43,'value_enum_email_payment','1'),
(44,'allow_cancel_request','1'),
(45,'cancel_before','2'),
(46,'use_qrcode','1'),
(47,'use_ssl','0'),
(48,'value_sch_include_phone','1'),
(49,'value_sch_include_country','0'),
(50,'value_sch_include_city','1'),
(51,'value_sch_include_state','0'),
(52,'value_sch_include_zip','0'),
(53,'value_sch_include_address','1'),
(54,'value_sch_include_captcha','1'),
(55,'pass_captcha','0'),
(56,'enable_termandcondition','0'),
(57,'article_id','686'),
(58,'activate_invoice_feature','0'),
(59,'send_invoice_to_customer','0'),
(60,'invoice_start_number','1'),
(61,'invoice_prefix',''),
(62,'invoice_number_length','5'),
(63,'invoice_format','<table border=\"0\" style=\"width: 100%;\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" width=\"100%\"><br />\r\n<table border=\"0\" style=\"width: 100%;\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td width=\"100%\"><br />\r\n<table border=\"0\" style=\"width: 100%;\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" valign=\"top\" width=\"50%\"><br />\r\n<table border=\"0\" style=\"width: 100%;\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Company Name:</td>\r\n<td align=\"left\">Ossolution Team</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">URL:</td>\r\n<td align=\"left\">http://www.joomdonation.com</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Phone:</td>\r\n<td align=\"left\">84-972409994</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">E-mail:</td>\r\n<td align=\"left\">contact@joomdonation.com</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Address:</td>\r\n<td align=\"left\">Lang Ha - Ba Dinh - Ha Noi</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td align=\"right\" valign=\"middle\" width=\"50%\"><img src=\"images/logo.jpg\" alt=\"\" width=\"129\" height=\"120\" /></td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"2\" align=\"left\" width=\"100%\">\r\n<table border=\"0\" style=\"width: 100%;\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" valign=\"top\" width=\"50%\"><br />\r\n<table border=\"0\" style=\"width: 589px;\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td colspan=\"2\" style=\"background-color: #d6d6d6;\" align=\"left\"><br />\r\n<h4 style=\"margin: 0px;\">Customer Information</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Name:</td>\r\n<td align=\"left\">[NAME]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Phone:</td>\r\n<td align=\"left\" width=\"50%\">[PHONE]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Email:</td>\r\n<td align=\"left\" width=\"50%\">[EMAIL]</td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"2\" style=\"background-color: #d6d6d6;\" align=\"left\"><br />\r\n<h4 style=\"margin: 0px;\">Details</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"2\" align=\"left\">[DETAILS]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(64,'enable_clickatell','0'),
(65,'clickatell_username',''),
(66,'clickatell_password',''),
(67,'clickatell_api','3419302'),
(68,'clickatell_senderid',''),
(69,'enable_eztexting','0'),
(70,'eztexting_username',''),
(71,'eztexting_password',''),
(72,'clickatell_defaultdialingcode','56'),
(73,'clickatell_showcodelist','0'),
(74,'clickatell_enable_unicode','0'),
(75,'sms_new_booking_to_admin','New Booking, customer just add new booking with ID {OrderID}'),
(76,'sms_new_booking_to_customer','You have booked service(s) from {business_name}, your order ID is {OrderID}'),
(77,'sms_payment_complete_to_admin','Payment complete, customer has paid for the order {OrderID}'),
(78,'sms_payment_complete_to_customer','You have paid successfully for service(s) from {business_name}, your order ID is {OrderID}'),
(79,'sms_reminder_notification','You have cancelled the booking request. Order ID {OrderID}'),
(80,'sms_order_cancelled_notification','Booking cancelled, customer has cancelled the order {OrderID}'),
(81,'order_status_changed_to_customer',''),
(82,'show_tax_in_cart','0'),
(83,'disable_calendar_in_off_date','0'),
(84,'show_occupied','1'),
(85,'use_js_popup','0'),
(86,'using_cart','0'),
(87,'show_calendar_box','0'),
(88,'start_day_in_week','monday'),
(89,'usingtab','1'),
(90,'booking_theme','1'),
(91,'hidetabs','1'),
(92,'employee_bar','1'),
(93,'show_employee_cost','0'),
(94,'show_number_timeslots_booking','0'),
(95,'show_dropdown_month_year','1'),
(96,'calendar_arrow','dark'),
(97,'header_style','btn btn-info'),
(98,'calendar_normal_style','btn btn-warning'),
(99,'calendar_activate_style','btn btn-info'),
(100,'calendar_currentdate_style','btn btn-danger'),
(101,'show_service_info_box','1'),
(102,'show_service_photo','1'),
(103,'show_service_description','1'),
(104,'show_booked_information','0'),
(105,'timeslot_background','#7BA1EB'),
(106,'show_details_and_orders','0'),
(107,'enable_acymailing','0');

/*(1, 'business_name', 'Services booking'),
(2, 'date_time_format', 'd.m.Y, H:i'),
(3, 'date_format', 'Y-m-d'),
(4, 'time_format', 'g:i A'),
(5, 'footer_content', 'Developed by Ossolution team'),
(6, 'meta_keyword', ''),
(7, 'meta_desc', ''),
(8, 'value_sch_reminder_enable', '1'),
(9, 'value_sch_reminder_email_before', '2'),
(10, 'employee_acl_group', '10'),
(11, 'start_day_in_week', 'sunday'),
(12, 'allow_registered_only', '1'),
(13, 'multiple_work', '1'),
(14, 'currency_format', 'USD'),
(15, 'currency_symbol_position', '1'),
(16, 'deposit_payment', '25'),
(17, 'enable_tax', '1'),
(18, 'tax_payment', '10'),
(19, 'step_format', '60'),
(20, 'disable_payments', '1'),
(21, 'enable_cardtypes', 'Visa,MasterCard,Discover,Amex'),
(22, 'value_sch_include_phone', '1'),
(23, 'value_sch_include_country', '1'),
(24, 'value_sch_include_city', '1'),
(25, 'value_sch_include_state', '1'),
(26, 'value_sch_include_zip', '0'),
(27, 'value_sch_include_address', '1'),
(28, 'value_sch_include_captcha', '1'),
(29, 'value_string_email_address', 'contact@osservicesbooking.com'),
(30, 'value_enum_email_confirmation', '2'),
(31, 'value_enum_email_payment', '1'),
(32, 'enable_termandcondition', '1'),
(33, 'article_id', '1'),
(34, 'activate_invoice_feature', '1'),
(35, 'send_invoice_to_customer', '1'),
(36, 'invoice_start_number', '1'),
(37, 'invoice_prefix', 'IV'),
(38, 'invoice_number_length', '5'),
(39, 'invoice_format', '&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;2&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;br /&gt;&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;2&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td width=&quot;100%&quot;&gt;&lt;br /&gt;&lt;table style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;2&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; valign=&quot;top&quot; width=&quot;50%&quot;&gt;&lt;br /&gt;&lt;table style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;2&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; width=&quot;50%&quot;&gt;Company Name:&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;Ossolution Team&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; width=&quot;50%&quot;&gt;URL:&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;http://www.joomdonation.com&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; width=&quot;50%&quot;&gt;Phone:&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;84-972409994&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; width=&quot;50%&quot;&gt;E-mail:&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;contact@joomdonation.com&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; width=&quot;50%&quot;&gt;Address:&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;Lang Ha - Ba Dinh - Ha Noi&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;td align=&quot;right&quot; valign=&quot;middle&quot; width=&quot;50%&quot;&gt;&lt;img src=&quot;images/logo.jpg&quot; width=&quot;129&quot; height=&quot;120&quot; /&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan=&quot;2&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;table style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;2&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; valign=&quot;top&quot; width=&quot;50%&quot;&gt;&lt;br /&gt;&lt;table width=&quot;589&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;2&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;background-color: #d6d6d6;&quot; colspan=&quot;2&quot; align=&quot;left&quot;&gt;&lt;br /&gt;&lt;h4 style=&quot;margin: 0px;&quot;&gt;Customer Information&lt;/h4&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; width=&quot;50%&quot;&gt;Name:&lt;/td&gt;&lt;td align=&quot;left&quot;&gt;[NAME]&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; width=&quot;50%&quot;&gt;Phone:&lt;/td&gt;&lt;td align=&quot;left&quot; width=&quot;50%&quot;&gt;[PHONE]&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; width=&quot;50%&quot;&gt;Email:&lt;/td&gt;&lt;td align=&quot;left&quot; width=&quot;50%&quot;&gt;[EMAIL]&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;background-color: #d6d6d6;&quot; colspan=&quot;2&quot; align=&quot;left&quot;&gt;&lt;br /&gt;&lt;h4 style=&quot;margin: 0px;&quot;&gt;Details&lt;/h4&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan=&quot;2&quot; align=&quot;left&quot;&gt;[DETAILS]&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;'),
(40, 'enable_clickatell', '0'),
(41, 'clickatell_username', ''),
(42, 'clickatell_password', ''),
(43, 'clickatell_api', '3419302'),
(44, 'clickatell_senderid', ''),
(45, 'clickatell_defaultdialingcode', '84'),
(46, 'clickatell_showcodelist', '1'),
(47, 'clickatell_enable_unicode', '0'),
(48, 'sms_new_booking_to_admin', 'New Booking, customer just add new booking with ID {OrderID}'),
(49, 'sms_new_booking_to_customer', 'You have booked service(s) from {business_name}, your order ID is {OrderID}'),
(50, 'sms_payment_complete_to_admin', 'Payment complete, customer has paid for the order {OrderID}'),
(51, 'sms_payment_complete_to_customer', 'You have paid successfully for service(s) from {business_name}, your order ID is {OrderID}'),
(52, 'sms_reminder_notification', 'You have cancelled the booking request. Order ID {OrderID}'),
(53, 'sms_order_cancelled_notification', 'Booking cancelled, customer has cancelled the order {OrderID}'),
(54, 'integrate_gcalendar', '0'),
(55, 'gcalendar_width', '700'),
(56, 'gcalendar_height', '600'),
(57, 'cancel_before', '5'),
(58, 'mobile_notification', ''),
(59, 'timezone1', ''),
(60, 'timezone2', ''),
(61, 'timezone3', ''),
(62, 'timezone4', ''),
(63, 'timezone5', ''),
(64, 'show_service_info_box', '1'),
(65, 'show_service_photo', '1'),
(66, 'show_service_description', '1'),
(67, 'load_bootstrap', '0'),
(68, 'use_ssl', '0'),
(69, 'csv_separator', ';'),
(70, 'header_style', 'btn btn-info'),
(71, 'calendar_normal_style', 'btn btn-warning'),
(72, 'calendar_activate_style', 'btn btn-info'),
(73, 'calendar_currentdate_style', 'btn btn-danger'),
(74, 'disable_payment_order_status', 'P'),
(75, 'show_occupied', '1'),
(76, 'employee_change_availability', '0'),
(77, 'disable_calendar_in_off_date', '0'),
(78, 'use_js_popup', '0'),
(79, 'using_cart', '1'),
(80, 'allow_registration', '1'),
(81, 'show_dropdown_month_year', '1'),
(82, 'calendar_arrow', 'dark'),
(83, 'allow_cancel_request', '1'),
(84, 'timeslot_background', '#7BA1EB'),
(85, 'employee_booking_only_today', '0'),
(86, 'employee_booking_only_today_desface','0');
*/